name: Review Marketplace

on:
  workflow_call:
    inputs:
      review-command:
        type: string
        default: "run"
        required: true
      pull-request-number:
        type: string
        required: true

jobs:
  action:
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ai-review
        uses: Nikita-Filonov/ai-review@v0.21.0
        env:
          AI_REVIEW_CONFIG_FILE_YAML: ./ci/review/config.yaml

          LLM__HTTP_CLIENT__API_TOKEN: ${{ secrets.OPENAI_API_KEY }}
          VCS__HTTP_CLIENT__API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VCS__PIPELINE__OWNER: ${{ github.repository_owner }}
          VCS__PIPELINE__REPO: ${{ github.event.repository.name }}
          VCS__PIPELINE__PULL_NUMBER: ${{ inputs.pull-request-number }}
        with:
          review-command: ${{ inputs.review-command }}
    runs-on: ubuntu-latest
