name: ğŸ¤– Review

on:
  workflow_dispatch:
    inputs:
      review-command:
        type: string
        default: "run"
        options: [ run, run-inline, run-context, run-summary ]
        required: true
      pull-request-number:
        type: string
        required: true
        description: 'Pull request number'

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: ğŸ¤– review
    uses: ./.github/workflows/reusable-review.yml
    with:
      review-command: ${{ inputs.review-command }}
      pull-request-number: ${{ inputs.pull-request-number }}
    secrets: inherit